routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();
Route::post('/password_reset/sendmail','Auth\AuthController@postSenMail')->name('auth.reset.password');
Route::get('reset-password/{token}', [
    'uses' => 'Auth\AuthController@resetPassword',
    'as' => 'auth.reset.resetpassword',
]);
Route::post('update-password', [
    'uses' => 'Auth\AuthController@updatePassword',
    'as' => 'auth.reset.updatepassword',
]);
Route::get('/home', 'HomeController@index')->name('home')->middleware('roleauth:admin|editor');
//Route::get('/home/vue', 'HomeController@vue')->name('home.vue');


Route::namespace('Admin')->middleware('roleauth:admin|editor')->prefix('admin')->group(function () {
	Route::get('/', [
        'uses' => 'IndexController@index',
        'as' => 'admin.index.index'
    ]);
	Route::get('/post/search', 'PostIndexController@search')->name('post.search');
	Route::get('/post/status', 'PostIndexController@status')->name('post.status');
	Route::get('/post/searchTags', 'PostIndexController@searchTags')->name('post.searchTags');
	Route::resource('post', 'PostIndexController');
    
    Route::get('/cat/search', 'CategoryController@search')->name('cat.search')->middleware('roleauth:admin');
    Route::resource('cat', 'CategoryController')->middleware('roleauth:admin');    
    Route::get('/tags/search', 'TagsController@search')->name('tags.search')->middleware('roleauth:admin');
    Route::resource('tags', 'TagsController')->middleware('roleauth:admin');

	Route::resource('groups', 'GroupsIndexController');
    Route::get('/profile', 'UserIndexController@profile')->name('profile');
    Route::get('/message', 'UserIndexController@message')->name('message');
    Route::post('/message', 'UserIndexController@postMessage')->name('user.postmessage');
    Route::post('/admin/users/profile/{id}', [
        'uses' => 'UserIndexController@postAddProfile',
        'as' => 'user.profile'
    ]);
    Route::post('/admin/users/change-avatar', [
        'uses' => 'UserIndexController@changeAvatar',
        'as' => 'user.avatar'
    ]);
    Route::resource('user', 'UserIndexController');


});

Route::get('notify', 'SendMessageController@index')->name('index');
Route::get('notify/send', 'SendMessageController@send')->name('send');
Route::post('notify/postMessage', 'SendMessageController@sendMessage')->name('postMessage');

Route::namespace('Vpublic')->group(function () {

    Route::get('/chat', 'ChatsController@index');
    Route::get('/chat/messages', 'ChatsController@fetchMessages');
    Route::post('/chat/messages', 'ChatsController@sendMessage');



    Route::get('/', [
        'uses' => 'PcIndexController@index',
        'as' => 'public.index'
    ]);
    Route::get('/search', [
        'uses' => 'PcIndexController@search',
        'as' => 'public.search'
    ]);
    Route::post('/review', [
        'uses' => 'PcIndexController@postReview',
        'as' => 'public.review'
    ])->middleware('auth');
    Route::get('/{cat}/{title}_{id}.html', [
        'uses' => 'PcIndexController@detail',
        'as' => 'public.detail'
    ]);
    Route::get('/{cat}_{id}', [
        'uses' => 'PcIndexController@category',
        'as' => 'public.category'
    ]);



});
Route::get('email', 'EmailController@sendEmail');

resources/views/admin/cat/add.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
  <h1>Thêm Danh Mục</h1>
@stop

@section('content')
<div class="row">
  <div class="col-md-10 col-md-offset-1">
  @if ($errors->any())
    <div class="alert alert-danger" role="alert">
      <ul>
      @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
      </ul>
    </div>
  @endif
  @if (session('msg-er'))
    <div class="alert alert-danger" role="alert">
      {{ session('msg-er') }}
    </div>
  @endif
  </div>
  <div class="col-md-8 col-md-offset-2">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Thêm Mới</h3>
      </div>
      <form action="{{ route('cat.store') }}" method="POST" class="form-horizontal" role="form" enctype="multipart/form-data" >
        {{ csrf_field() }}
        <div class="box-body">
          <div class="form-group">
             <label for="name" class="col-sm-2 control-label">Danh mục</label>
              <div class="col-sm-8">
                 <input type="text" name="name" id="name" class="form-control" value="{{ old('name') }}">
              </div>
         </div>
          <div class="form-group">
             <label for="sort" class="col-sm-2 control-label">Sắp xếp</label>
              <div class="col-sm-8">
                 <input type="number" name="sort" id="sort" class="form-control" value="{{ old('sort',100) }}">
              </div>
         </div> 
        </div>         
        <div class="box-footer text-center ">
            <button type="submit" class="btn btn-success">Save</button>
            <a href="{{ route('cat.index') }}" class="btn btn-primary" onclick="return confirm('Các thay đổi chưa được lưu. Tiếp tục?') ">Back</a>
        </div>         
    </form>
      
    </div>
    
  </div>
</div>
@stop

resources/views/admin/cat/edit.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
  <h1>Sửa Danh Mục</h1>
@stop

@section('content')
<div class="row">
  <div class="col-md-10 col-md-offset-1">
  @if ($errors->any())
    <div class="alert alert-danger" role="alert">
      <ul>
      @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
      </ul>
    </div>
  @endif
  @if (session('msg-er'))
    <div class="alert alert-danger" role="alert">
      {{ session('msg-er') }}
    </div>
  @endif
  </div>
  <div class="col-md-8 col-md-offset-2">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Thay đổi</h3>
      </div>
      <form action="{{ route('cat.update',$old_item->id) }}" method="post" class="form-horizontal" role="form"  >
        {{ csrf_field() }}
        @method('PUT')
        <div class="box-body">
          <div class="form-group">
             <label for="name" class="col-sm-2 control-label">Danh mục</label>
              <div class="col-sm-8">
                 <input type="text" name="name" id="name" class="form-control" value="{{ old('name',$old_item->name) }}">
              </div>
         </div>
         <div class="form-group">
             <label for="sort" class="col-sm-2 control-label">Sắp xếp</label>
              <div class="col-sm-8">
                 <input type="number" name="sort" id="sort" class="form-control" value="{{ old('sort',$old_item->sort) }}">
              </div>
         </div>  
        </div>         
        <div class="box-footer text-center ">
            <button type="submit" class="btn btn-success">Save</button>
            <a href="{{ route('cat.index') }}" class="btn btn-primary" onclick="return confirm('Các thay đổi chưa được lưu. Tiếp tục?') ">Back</a>
        </div>         
    </form>
      
    </div>
    
  </div>
</div>
@stop

resources/views/admin/cat/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE - Danh mục')

@section('content_header')
    <h1>Danh mục</h1>
@stop

@section('content')
    <div class="card-body">
        @if (session('msg'))
            <div class="alert alert-success" role="alert">
                {{ session('msg') }}
            </div>
        @endif
        @if (session('msg-er'))
            <div class="alert alert-danger" role="alert">
                {{ session('msg-er') }}
            </div>
        @endif
    </div>
    <div class="container-fluid">
        <form action="{{ route('cat.create') }}" method="get" style="display: inline;" id="form-create" >
            <button type="submit" class="btn bg-orange margin"><i class="fa fa-fw fa-plus-square"></i> Thêm</button>
        </form>
        <form id="delete-form" action="" method="POST" style="display: none;">
            @csrf
            @method('DELETE')
        </form>
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Danh mục bài viết</h3>
                        <form id="search-form" action="{{ route('cat.search') }}" method="get" style="display: none;">
                            @csrf
                        </form>
                        <div class="box-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="cat_search" class="form-control pull-right" placeholder="Search" form="search-form" value="{{ request('cat_search') ? request('cat_search') : '' }}">
                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default" form="search-form"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                <!-- /.box-header -->
                    <div class="box-body table-responsive no-padding">
                    <table class="table table-hover table-bordered">
                        <tbody><tr>
                            <th class="text-center">ID</th>
                            <th>Tên Danh mục</th>
                            <th>Số bài viết</th>
                            <th>Action</th>
                        </tr>
                        @if (!empty($objItems))
                            @foreach ($objItems as $item)
                            <tr>
                                <td class="text-center">{{ $item->id }}</td>
                                <td>{{ $item->name }}</td>
                                <td>{{ $item->posts->count() }}</td>
                                <td style="width: 140px">
                                    <form id="edit{{ $item->id }}" action="{{ route('cat.edit',$item->id) }}" method="get" style="display: inline;" >
                                        <a href="javascript:void(0)" class="btn btn-info" onclick="editCat({{ $item->id }})" ><i class="fa fa-fw fa-pencil-square"></i></a>
                                    </form>
                                    <a class="btn btn-danger" href="javascript:void(0)"  onclick="deleteCat({{ $item->id }})"><i class="fa fa-fw fa-trash"></i></a>
                                </td>
                            </tr>
                            @endforeach
                        @endif
                        </tbody></table>
                    </div>
                <!-- /.box-body -->
                </div>
            <!-- /.box -->
            </div>
        </div>
        <ul class="pagination">
            {{ $objItems->appends(Request::except('page'))->links() }}
        </ul>
    </div>
@stop
@section('js')
<script>
    function deleteCat(cid) {
        if (confirm('Bạn có chắc muốn xóa?')) {
            var route = '/admin/cat/'+cid;
            $('#delete-form').attr('action',route);
            $('#delete-form').submit();
        }
    }
    function editCat(cid) {
        var editform = $('#edit'+cid);
        $(editform).submit();
    }
</script>
@stop