routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();
Route::post('/password_reset/sendmail','Auth\AuthController@postSenMail')->name('auth.reset.password');
Route::get('reset-password/{token}', [
    'uses' => 'Auth\AuthController@resetPassword',
    'as' => 'auth.reset.resetpassword',
]);
Route::post('update-password', [
    'uses' => 'Auth\AuthController@updatePassword',
    'as' => 'auth.reset.updatepassword',
]);
Route::get('/home', 'HomeController@index')->name('home')->middleware('roleauth:admin|editor');
//Route::get('/home/vue', 'HomeController@vue')->name('home.vue');


Route::namespace('Admin')->middleware('roleauth:admin|editor')->prefix('admin')->group(function () {
	Route::get('/', [
        'uses' => 'IndexController@index',
        'as' => 'admin.index.index'
    ]);
	Route::get('/post/search', 'PostIndexController@search')->name('post.search');
	Route::get('/post/status', 'PostIndexController@status')->name('post.status');
	Route::get('/post/searchTags', 'PostIndexController@searchTags')->name('post.searchTags');
	Route::resource('post', 'PostIndexController');
    
    Route::get('/cat/search', 'CategoryController@search')->name('cat.search')->middleware('roleauth:admin');
    Route::resource('cat', 'CategoryController')->middleware('roleauth:admin');    
    Route::get('/tags/search', 'TagsController@search')->name('tags.search')->middleware('roleauth:admin');
    Route::resource('tags', 'TagsController')->middleware('roleauth:admin');

	Route::resource('groups', 'GroupsIndexController');
    Route::get('/profile', 'UserIndexController@profile')->name('profile');
    Route::get('/message', 'UserIndexController@message')->name('message');
    Route::post('/message', 'UserIndexController@postMessage')->name('user.postmessage');
    Route::post('/admin/users/profile/{id}', [
        'uses' => 'UserIndexController@postAddProfile',
        'as' => 'user.profile'
    ]);
    Route::post('/admin/users/change-avatar', [
        'uses' => 'UserIndexController@changeAvatar',
        'as' => 'user.avatar'
    ]);
    Route::resource('user', 'UserIndexController');


});

Route::get('notify', 'SendMessageController@index')->name('index');
Route::get('notify/send', 'SendMessageController@send')->name('send');
Route::post('notify/postMessage', 'SendMessageController@sendMessage')->name('postMessage');

Route::namespace('Vpublic')->group(function () {

    Route::get('/chat', 'ChatsController@index');
    Route::get('/chat/messages', 'ChatsController@fetchMessages');
    Route::post('/chat/messages', 'ChatsController@sendMessage');



    Route::get('/', [
        'uses' => 'PcIndexController@index',
        'as' => 'public.index'
    ]);
    Route::get('/search', [
        'uses' => 'PcIndexController@search',
        'as' => 'public.search'
    ]);
    Route::post('/review', [
        'uses' => 'PcIndexController@postReview',
        'as' => 'public.review'
    ])->middleware('auth');
    Route::get('/{cat}/{title}_{id}.html', [
        'uses' => 'PcIndexController@detail',
        'as' => 'public.detail'
    ]);
    Route::get('/{cat}_{id}', [
        'uses' => 'PcIndexController@category',
        'as' => 'public.category'
    ]);



});
Route::get('email', 'EmailController@sendEmail');

app/Http/Controllers/Admin/TagsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Model\PostTag\PostTagIndex;
use App\Model\Tags\TagsIndex;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class TagsController extends Controller
{
    public function __construct(TagsIndex $objTagsIndex)
    {
        $this->objTagsIndex = $objTagsIndex;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $objItems = $this->objTagsIndex->getItemsIndex();
        return view('admin.tags.index',compact('objItems'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tags.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $v = Validator::make($request->all(), [
            'tag' => 'required|unique:tags|max:255',
        ],[
            'tag.required' =>'Nhập Tags',
            'tag.max'      =>'Nhập Tags không quá :max ký tự',
            'tag.unique'   => 'Tên Tags đã tồn tại',
        ]);

        if ($v->fails())
        {
            return redirect()->back()->withErrors($v->errors());
        }

        $arItem = [
            'tag' => trim($request->tag),
        ];
        
        if($this->objTagsIndex->addItem($arItem)) {
            return redirect()->route('tags.index')->with('msg','Thêm thành công');
        } else {
            return redirect()->back()->with('msg-er','Có lỗi xảy ra');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $old_item = TagsIndex::find($id);
        return view('admin.tags.edit',compact('old_item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $old_item = TagsIndex::find($id);
        $unique = ( $old_item->tag != trim($request->tag) )? '|unique:tags' : '';
        $v = Validator::make($request->all(), [
            'tag' => 'required|max:255'.$unique,
        ],[
            'tag.required' =>'Nhập Tags',
            'tag.max'      =>'Nhập Tags không quá :max ký tự',
            'tag.unique'   => 'Tên Tags đã tồn tại',
        ]);

        if ($v->fails())
        {
            return redirect()->back()->withErrors($v->errors());
        }

        $arItem = [
            'tag' => trim($request->tag),
        ];
        if($this->objTagsIndex->editItem($arItem,$id)) {
            return redirect()->route('tags.index')->with('msg','Sửa thành công');
        } 
        return redirect()->route('tags.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tag = TagsIndex::find($id);
        $count = $tag->posts->count();
        if (!$count) {
            if($this->objTagsIndex->delItem($id)) {
                return redirect()->route('tags.index')->with('msg','Xóa thành công');
            } else {
                return redirect()->back()->with('msg-er','Có lỗi xảy ra');
            }
        }
        else {
            $this->objTagsIndex->delItem($id);
            $objmPostTagIndex = new PostTagIndex();
            $objmPostTagIndex->delItemByTag($id);
            return redirect()->route('tags.index')->with('msg','Xóa thành công');
        }
    }
    /**
     * @param  Request
     * @return [type]
     */
    public function search(Request $request)
    {
        if(!empty($request->tags_search)) {
            $search = trim($request->tags_search);
            $objItems = $this->objTagsIndex->getItemsBySearch($search);
            return view('admin.tags.index',compact('objItems'));
        } else {
            return redirect()->route('tags.index');
        }
        
    }
}

resources/views/admin/tags/add.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
  <h1>Thêm Tags</h1>
@stop

@section('content')
<div class="row">
  <div class="col-md-10 col-md-offset-1">
  @if ($errors->any())
    <div class="alert alert-danger" role="alert">
      <ul>
      @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
      </ul>
    </div>
  @endif
  @if (session('msg-er'))
    <div class="alert alert-danger" role="alert">
      {{ session('msg-er') }}
    </div>
  @endif
  </div>
  <div class="col-md-8 col-md-offset-2">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Thêm Mới</h3>
      </div>
      <form action="{{ route('tags.store') }}" method="POST" class="form-horizontal" role="form" enctype="multipart/form-data" >
        {{ csrf_field() }}
        <div class="box-body">
          <div class="form-group">
             <label for="tag" class="col-sm-2 control-label">Tag</label>
              <div class="col-sm-8">
                 <input type="text" name="tag" id="tag" class="form-control" value="{{ old('tag') }}">
              </div>
         </div>
        </div>         
        <div class="box-footer text-center ">
            <button type="submit" class="btn btn-success">Save</button>
            <a href="{{ route('tags.index') }}" class="btn btn-primary" onclick="return confirm('Các thay đổi chưa được lưu. Tiếp tục?') ">Back</a>
        </div>         
    </form>
      
    </div>
    
  </div>
</div>
@stop

resources/views/admin/tags/edit.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
  <h1>Sửa Tags</h1>
@stop

@section('content')
<div class="row">
  <div class="col-md-10 col-md-offset-1">
  @if ($errors->any())
    <div class="alert alert-danger" role="alert">
      <ul>
      @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
      </ul>
    </div>
  @endif
  @if (session('msg-er'))
    <div class="alert alert-danger" role="alert">
      {{ session('msg-er') }}
    </div>
  @endif
  </div>
  <div class="col-md-8 col-md-offset-2">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Thay đổi</h3>
      </div>
      <form action="{{ route('tags.update',$old_item->id) }}" method="post" class="form-horizontal" role="form"  >
        {{ csrf_field() }}
        @method('PUT')
        <div class="box-body">
          <div class="form-group">
              <label for="tag" class="col-sm-2 control-label">Tag</label>
              <div class="col-sm-8">
                 <input type="text" name="tag" id="tag" class="form-control" value="{{ old('tag',$old_item->tag) }}">
              </div>
          </div>
        </div>         
        <div class="box-footer text-center ">
            <button type="submit" class="btn btn-success">Save</button>
            <a href="{{ route('tags.index') }}" class="btn btn-primary" onclick="return confirm('Các thay đổi chưa được lưu. Tiếp tục?') ">Back</a>
        </div>         
    </form>
    </div>
  </div>
</div>
@stop

resources/views/admin/tags/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE - Danh mục')

@section('content_header')
    <h1>Tags Bài viết</h1>
@stop

@section('content')
    <div class="card-body">
        @if (session('msg'))
            <div class="alert alert-success" role="alert">
                {{ session('msg') }}
            </div>
        @endif
        @if (session('msg-er'))
            <div class="alert alert-danger" role="alert">
                {{ session('msg-er') }}
            </div>
        @endif
    </div>
    <div class="container-fluid">
        <form action="{{ route('tags.create') }}" method="get" style="display: inline;" id="form-create" >
            <button type="submit" class="btn bg-orange margin"><i class="fa fa-fw fa-plus-square"></i> Thêm</button>
        </form>
        <form id="delete-form" action="" method="POST" style="display: none;">
            @csrf
            @method('DELETE')
        </form>
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Danh mục bài viết</h3>
                        <form id="search-form" action="{{ route('tags.search') }}" method="get" style="display: none;">
                            @csrf
                        </form>
                        <div class="box-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="tags_search" class="form-control pull-right" placeholder="Search" form="search-form" value="{{ request('tags_search') ? request('tags_search') : '' }}">
                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default" form="search-form"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                <!-- /.box-header -->
                    <div class="box-body table-responsive no-padding">
                    <table class="table table-hover table-bordered">
                        <tbody><tr>
                            <th class="text-center">ID</th>
                            <th>Tên Tag</th>
                            <th>Bài viết</th>
                            <th>Action</th>
                        </tr>
                        @if (!empty($objItems))
                            @foreach ($objItems as $item)
                            <tr>
                                <td class="text-center">{{ $item->id }}</td>
                                <td>{{ $item->tag }}</td>
                                <td>{{ $item->posts->count() }}</td>
                                <td style="width: 140px">
                                    <form id="edit{{ $item->id }}" action="{{ route('tags.edit',$item->id) }}" method="get" style="display: inline;" >
                                        <a href="javascript:void(0)" class="btn btn-info" onclick="editCat({{ $item->id }})" ><i class="fa fa-fw fa-pencil-square"></i></a>
                                    </form>
                                    <a class="btn btn-danger" href="javascript:void(0)"  onclick="deleteCat({{ $item->id }},{{ $item->posts->count() }})"><i class="fa fa-fw fa-trash"></i></a>
                                </td>
                            </tr>
                            @endforeach
                        @endif
                        </tbody></table>
                    </div>
                <!-- /.box-body -->
                </div>
            <!-- /.box -->
            </div>
        </div>
        <ul class="pagination">
            {{ $objItems->appends(Request::except('page'))->links() }}
        </ul>
    </div>
@stop
@section('js')
<script>
    function deleteCat(cid,count) {
        if(count>0){
            if (confirm('Một số bài viết còn chứa Tags này! Tiếp tục xóa?')) {
                var route = '/admin/tags/'+cid;
                $('#delete-form').attr('action',route);
                $('#delete-form').submit();
            } 
        }else if(confirm('Bạn có chắc muốn xóa?')) {
            var route = '/admin/tags/'+cid;
            $('#delete-form').attr('action',route);
            $('#delete-form').submit();
        }
    }
    function editCat(cid) {
        var editform = $('#edit'+cid);
        $(editform).submit();
    }
</script>
@stop